/* The following code was generated by JFlex 1.4.3 on 8/26/13 12:43 AM */

package ru.usb7.idea.plugin.perl;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import ru.usb7.idea.plugin.perl.psi.PerlTypes;
import com.intellij.psi.TokenType;

/* *
   * PACKAGE_KEYWORD
   * MODULE_NAME
   * SEMICOLON
   * USE_REQURE_KEYWORD
   * INCLUDE_LIST
   * SPECIAL_BLOCK_KEYWORD
   * VARIABLE_DECLARATION_KEYWORD
   * EVAL_KEYWORD
   * CURLYBRACKET_OPEN
   * CURLYBRACKET_CLOSE
   * COMMENT
   * PERLPOD_START
   * PERLPOD_CONTENT
   * PERLPOD_END
   * SCALAR_SIGIL
   * ID
   * ARRAY_SIGIL
   * HASH_SIGIL
   * LITERAL_START
   * LITERAL_CONTENT
   * LITERAL_END
   */


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/26/13 12:43 AM from the specification file
 * <tt>/media/firefish/data/projects/idea_plugin/src/ru/usb7/idea/plugin/perl/Perl.flex</tt>
 */
class PerlLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int WAITING_QUOTE_STRING_END = 2;
  public static final int WAITING_PERLPOD_END = 4;
  public static final int YYINITIAL = 0;
  public static final int WAITING_MODULE = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\1\1\0\1\4\1\2\22\0\1\27\2\0\1\14"+
    "\1\17\1\21\1\0\1\7\1\0\1\0\6\0\12\6\1\46\1\3"+
    "\1\0\1\10\1\0\1\0\1\20\1\5\1\33\1\42\1\45\1\34"+
    "\1\5\1\35\1\43\1\36\1\5\1\44\2\5\1\37\5\5\1\41"+
    "\1\40\5\5\1\0\1\47\1\0\3\0\1\23\1\5\1\11\1\5"+
    "\1\26\1\5\1\25\3\5\1\24\2\5\1\50\1\5\1\22\1\32"+
    "\1\31\1\30\1\13\1\12\5\5\1\15\1\0\1\16\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\5\1\7\1\10\1\11\1\12\1\13\1\14\7\5"+
    "\1\15\1\16\1\15\2\17\1\1\1\20\1\21\1\22"+
    "\10\5\1\15\1\17\2\0\4\5\1\23\3\5\2\0"+
    "\1\24\5\5\1\25\3\5\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\244\0\315\0\244"+
    "\0\366\0\u011f\0\244\0\u0148\0\u0171\0\u019a\0\244\0\244"+
    "\0\244\0\244\0\244\0\u01c3\0\u01ec\0\u0215\0\u023e\0\u0267"+
    "\0\u0290\0\u02b9\0\u02e2\0\244\0\u030b\0\u0334\0\u035d\0\u0386"+
    "\0\366\0\u03af\0\u03d8\0\u0401\0\u042a\0\u0453\0\u047c\0\u04a5"+
    "\0\u04ce\0\u04f7\0\u0520\0\244\0\u0549\0\u0572\0\u059b\0\u05c4"+
    "\0\u05ed\0\u0616\0\u063f\0\u011f\0\u0668\0\u0691\0\u06ba\0\u06e3"+
    "\0\u070c\0\244\0\u0735\0\u075e\0\u0787\0\u07b0\0\u07d9\0\244"+
    "\0\u0802\0\u082b\0\u0854\0\244";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\5\1\13"+
    "\1\14\1\12\1\15\1\12\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\4\12\1\11\1\12\1\25\1\12"+
    "\1\26\1\27\1\12\1\30\1\12\1\31\1\12\1\32"+
    "\3\12\2\5\1\12\1\33\1\6\1\7\4\33\1\34"+
    "\37\33\1\35\1\33\10\36\1\37\40\36\3\40\1\10"+
    "\1\41\1\42\3\40\3\42\6\40\5\42\1\41\16\42"+
    "\2\40\1\42\52\0\1\6\53\0\1\11\22\0\1\11"+
    "\26\0\2\12\2\0\3\12\6\0\5\12\1\0\16\12"+
    "\2\0\1\12\5\0\1\43\3\0\3\43\6\0\5\43"+
    "\1\0\16\43\2\0\1\43\5\0\2\12\2\0\3\12"+
    "\6\0\5\12\1\0\1\44\15\12\2\0\1\12\1\16"+
    "\2\0\46\16\5\0\2\12\2\0\3\12\6\0\1\12"+
    "\1\45\3\12\1\0\16\12\2\0\1\12\5\0\2\12"+
    "\2\0\3\12\6\0\4\12\1\46\1\0\16\12\2\0"+
    "\1\12\5\0\2\12\2\0\3\12\6\0\5\12\1\0"+
    "\4\12\1\47\11\12\2\0\1\12\5\0\2\12\2\0"+
    "\3\12\6\0\5\12\1\0\7\12\1\50\6\12\2\0"+
    "\1\12\5\0\2\12\2\0\3\12\6\0\5\12\1\0"+
    "\7\12\1\51\6\12\2\0\1\12\5\0\2\12\2\0"+
    "\3\12\6\0\5\12\1\0\7\12\1\52\6\12\2\0"+
    "\1\12\5\0\2\12\2\0\3\12\6\0\5\12\1\0"+
    "\13\12\1\53\2\12\2\0\1\12\1\33\2\0\4\33"+
    "\1\0\37\33\1\0\1\33\7\0\1\54\21\0\1\54"+
    "\16\0\1\54\10\36\1\0\40\36\10\0\1\55\1\56"+
    "\37\0\3\40\3\0\3\40\3\0\6\40\24\0\2\40"+
    "\6\0\2\42\2\0\3\42\6\0\5\42\1\0\16\42"+
    "\1\57\1\0\1\42\1\43\2\0\46\43\5\0\2\12"+
    "\2\0\3\12\6\0\4\12\1\60\1\0\16\12\2\0"+
    "\1\12\5\0\2\12\2\0\1\61\2\12\6\0\5\12"+
    "\1\0\16\12\2\0\1\12\5\0\2\12\2\0\3\12"+
    "\6\0\5\12\1\0\2\12\1\62\13\12\2\0\1\12"+
    "\5\0\2\12\2\0\3\12\6\0\5\12\1\0\5\12"+
    "\1\63\10\12\2\0\1\12\5\0\2\12\2\0\3\12"+
    "\6\0\5\12\1\0\15\12\1\64\2\0\1\12\5\0"+
    "\2\12\2\0\3\12\6\0\5\12\1\0\6\12\1\65"+
    "\7\12\2\0\1\12\5\0\2\12\2\0\3\12\6\0"+
    "\5\12\1\0\6\12\1\66\7\12\2\0\1\12\5\0"+
    "\2\12\2\0\3\12\6\0\5\12\1\0\4\12\1\67"+
    "\11\12\2\0\1\12\10\0\1\55\52\0\1\70\104\0"+
    "\1\71\7\0\2\12\2\0\3\12\6\0\5\12\1\72"+
    "\16\12\2\0\1\12\5\0\2\12\2\0\3\12\6\0"+
    "\2\12\1\73\2\12\1\0\16\12\2\0\1\12\5\0"+
    "\2\12\2\0\1\12\1\74\1\12\6\0\5\12\1\0"+
    "\16\12\2\0\1\12\5\0\2\12\2\0\3\12\6\0"+
    "\5\12\1\0\6\12\1\75\7\12\2\0\1\12\5\0"+
    "\2\12\2\0\3\12\6\0\5\12\1\0\11\12\1\64"+
    "\4\12\2\0\1\12\5\0\2\12\2\0\3\12\6\0"+
    "\5\12\1\0\11\12\1\76\4\12\2\0\1\12\5\0"+
    "\2\12\2\0\3\12\6\0\5\12\1\0\12\12\1\77"+
    "\3\12\2\0\1\12\13\0\1\100\42\0\1\42\3\0"+
    "\3\42\6\0\5\42\1\0\16\42\2\0\1\42\5\0"+
    "\2\12\2\0\3\12\6\0\1\12\1\101\3\12\1\0"+
    "\16\12\2\0\1\12\5\0\2\12\2\0\3\12\6\0"+
    "\5\12\1\0\1\12\1\44\14\12\2\0\1\12\5\0"+
    "\2\12\2\0\3\12\6\0\5\12\1\0\7\12\1\64"+
    "\6\12\2\0\1\12\5\0\2\12\2\0\3\12\6\0"+
    "\5\12\1\0\12\12\1\32\3\12\2\0\1\12\5\0"+
    "\2\12\2\0\3\12\6\0\5\12\1\0\14\12\1\64"+
    "\1\12\2\0\1\12\5\0\2\12\2\0\3\12\6\0"+
    "\3\12\1\102\1\12\1\0\16\12\2\0\1\12\5\0"+
    "\2\12\2\0\3\12\6\0\4\12\1\103\1\0\16\12"+
    "\2\0\1\12\5\0\2\12\2\0\3\12\6\0\5\12"+
    "\1\104\16\12\2\0\1\12";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2173];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\1\1\1\11\2\1\1\11\3\1\5\11"+
    "\10\1\1\11\17\1\1\11\1\1\2\0\10\1\2\0"+
    "\1\11\5\1\1\11\3\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[68];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  PerlLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  PerlLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { yybegin(YYINITIAL); return PerlTypes.MODULE_NAME;
          }
        case 23: break;
        case 22: 
          { yybegin(WAITING_MODULE); return PerlTypes.PACKAGE_KEYWORD;
          }
        case 24: break;
        case 8: 
          { yybegin(YYINITIAL); return PerlTypes.CURLYBRACKET_OPEN;
          }
        case 25: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 26: break;
        case 13: 
          { yybegin(WAITING_QUOTE_STRING_END); return PerlTypes.LITERAL_CONTENT;
          }
        case 27: break;
        case 7: 
          { yybegin(YYINITIAL); return PerlTypes.COMMENT;
          }
        case 28: break;
        case 2: 
          { yybegin(YYINITIAL); return PerlTypes.CRLF;
          }
        case 29: break;
        case 16: 
          { yybegin(WAITING_MODULE); return PerlTypes.MODULE_NAME;
          }
        case 30: break;
        case 9: 
          { yybegin(YYINITIAL); return PerlTypes.CURLYBRACKET_CLOSE;
          }
        case 31: break;
        case 6: 
          { yybegin(WAITING_QUOTE_STRING_END); return PerlTypes.LITERAL_START;
          }
        case 32: break;
        case 5: 
          { yybegin(YYINITIAL); return PerlTypes.ID;
          }
        case 33: break;
        case 11: 
          { yybegin(YYINITIAL); return PerlTypes.ARRAY_SIGIL;
          }
        case 34: break;
        case 10: 
          { yybegin(YYINITIAL); return PerlTypes.SCALAR_SIGIL;
          }
        case 35: break;
        case 15: 
          { yybegin(WAITING_PERLPOD_END); return PerlTypes.PERLPOD_CONTENT;
          }
        case 36: break;
        case 14: 
          { yybegin(YYINITIAL); return PerlTypes.LITERAL_END;
          }
        case 37: break;
        case 20: 
          { yybegin(WAITING_MODULE); return PerlTypes.USE_REQURE_KEYWORD;
          }
        case 38: break;
        case 21: 
          { yybegin(YYINITIAL); return PerlTypes.PERLPOD_END;
          }
        case 39: break;
        case 4: 
          { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
          }
        case 40: break;
        case 19: 
          { yybegin(YYINITIAL); return PerlTypes.SPECIAL_BLOCK_KEYWORD;
          }
        case 41: break;
        case 18: 
          { yybegin(WAITING_PERLPOD_END); return PerlTypes.PERLPOD_START;
          }
        case 42: break;
        case 3: 
          { yybegin(YYINITIAL); return PerlTypes.SEMICOLON;
          }
        case 43: break;
        case 12: 
          { yybegin(YYINITIAL); return PerlTypes.HASH_SIGIL;
          }
        case 44: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
